"""baseline

Revision ID: 1c6021d6984b
Revises: 
Create Date: 2026-09-05 12:41:02.606435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c6021d6984b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False, comment='租户主键，使用 UUID 避免多环境/分片时的自增冲突'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='租户名称，全局唯一'),
    sa.Column('api_key_hash', sa.String(length=128), nullable=False, comment='API Key 的 bcrypt 哈希；鉴权时用明文 Verify，禁止把哈希当查找键'),
    sa.Column('api_key_prefix', sa.String(length=32), nullable=False, comment='明文 Key 前 24 位，仅用于定位候选行，不能单独通过鉴权'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（UTC）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_hash'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tenants_api_key_prefix'), 'tenants', ['api_key_prefix'], unique=True)
    op.create_table('task_records',
    sa.Column('task_id', sa.UUID(), nullable=False, comment='任务 ID，对外返回给调用方用于查询与追踪'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='所属租户，级联删除保证租户下线时任务一并清理'),
    sa.Column('status', sa.Enum('PENDING', 'WAITING', 'RUNNING', 'SUCCESS', 'FAILED', 'DLQ', 'CANCELED', name='task_status'), nullable=False, comment='任务状态，新建时固定为 PENDING'),
    sa.Column('task_type', sa.String(length=128), nullable=False, comment='任务类型，例如 email.send / order.sync，供后续路由到对应处理器'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='任务载荷，任意 JSON 对象'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='优先级，数值越大越先被 Worker 拾取'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='已失败次数，默认 0；达到 WORKER_MAX_RETRIES 后进入 DLQ'),
    sa.Column('error_msg', sa.Text(), nullable=True, comment='最近一次失败的异常堆栈，进入 DLQ 后便于人工排查'),
    sa.Column('execute_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='计划执行时间；未到期时只存在于延迟 ZSet，到期后由 Dispatcher 转入 Stream'),
    sa.Column('workflow_id', sa.UUID(), nullable=True, comment='所属 DAG 工作流；独立任务为空'),
    sa.Column('upstream_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='父任务 UUID 列表；全部 SUCCESS 后本任务才可从 WAITING 转为 PENDING'),
    sa.Column('downstream_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='子任务 UUID 列表；本任务 SUCCESS 后尝试唤醒，DLQ 后级联 CANCELED'),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='成功执行后的返回值，供下游 XCom 注入与结果查询'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间（UTC）'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index('ix_task_records_status_priority_created', 'task_records', ['status', 'priority', 'created_at'], unique=False)
    op.create_index('ix_task_records_status_updated_at', 'task_records', ['status', 'updated_at'], unique=False)
    op.create_index('ix_task_records_tenant_status', 'task_records', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_task_records_workflow_id', 'task_records', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_records_workflow_id', table_name='task_records')
    op.drop_index('ix_task_records_tenant_status', table_name='task_records')
    op.drop_index('ix_task_records_status_updated_at', table_name='task_records')
    op.drop_index('ix_task_records_status_priority_created', table_name='task_records')
    op.drop_table('task_records')
    op.drop_index(op.f('ix_tenants_api_key_prefix'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
